Repository valleweb/valle-select, pull requests merged in 2020-03, with the labels that each got.

#21 Modulating the main file component for a easily maintenance
  demo/index.html
  main.js
  package.json
  test/valle-option_test.html
  test/valle-option_test.js
  test/valle-select_integration_test.html
  test/valle-select_integration_test.js
  test/valle-select_test.js
  valle-option.js
  valle-select.js
Labels: Component, Enhancement, Polymer 3x, Review

#23 Fix listbox height and position
  valle-select.js
Labels: Ok review

#24 Adjust height to new default size
  package.json
  valle-select.js
Labels: Review
